// User Sginup
export const SIGNUP_START = 'SIGNUP_START'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

// User Signin
export const SIGNIN_START = 'SIGNIN_START'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_ERROR = 'SIGNIN_ERROR'

// User Signin
export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

// Set User
export const SET_USER = 'SET_USER'

export const SET_USER_START = 'SET_USER_START'
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS'
export const SET_USER_ERROR = 'SET_USER_ERROR'

export const GOOGLE_OAUTH_START = 'GOOGLE_OAUTH_START'
export const GOOGLE_OAUTH_SUCCESS = 'GOOGLE_OAUTH_SUCCESS'
export const GOOGLE_OAUTH_ERROR = 'GOOGLE_OAUTH_ERROR'

export const FACEBOOK_OAUTH_START = 'FACEBOOK_OAUTH_START'
export const FACEBOOK_OAUTH_SUCCESS = 'FACEBOOK_OAUTH_SUCCESS'
export const FACEBOOK_OAUTH_ERROR = 'FACEBOOK_OAUTH_ERROR'
